### ISSUE TITLE
M2 spacers

### ISSUE THREAD

**Issue by idank** [aki27kbd/trackball_module#1]
Hi, where do you buy the M2 spacers? Are they on aliexpress? Thanks!

**Comment by protieusz** [comment]
I bought mine from here https://vi.aliexpress.com/item/32879956829.html?

**Comment by idank** [comment]
Yeah but those are gold, it doesn't seem there are silver ones on
aliexpress.

**Comment by PancakeGoon** [comment]
Just keep searching, there are spacers & standoffs of all shapes, sizes &
colors on Ali (don't know your region, I'm in the US). Just search for "M2 round standoff" (threaded: screws can be tightened directly into them from both sides) or spacers (UN-threaded: requires screws that are long enough to pass through the whole assembly, with a nut screwed onto the end on the other side) depending on your preference.  
>   
>  
[*TIP*] AliExpress uses a "Smart" Algorithm that tends to give weak & repetitive results from promoted vendors until you start clicking through the related 'Recommended Products' that are closer to your wants a bit.

**Comment by PancakeGoon** [comment]
> Yeah but those are gold, it doesn't seem there are silver ones on
> aliexpress.
> 
> >
> 

Here are some silver & round M2 threaded standoffs in an assortment of lengths (6mm, 8mm, 10mm, etc.):  
https://a.aliexpress.com/_mM2uRKA  
> 
And here are some HEXAGONAL sets of standoffs in M2/M2.5/M3 and an assortment of colors & lengths:  
https://a.aliexpress.com/_ms5tF0i  
>  
>  
I tend to hate M2 standoffs & screws as they're so small and lack sturdiness, as well as being generally harder to find in more unique shapes, styles & colors. I really wish KB designers would bump the "standard" up to at least 3mm/M3, and I know this isn't exactly a hot take. But I have found enough stuff to get by on Ali & other vendors for aesthetically-pleasing M2 spacers/standoffs & hardware to get by (custom FPV/Drone parts stores are a solid lead).  
  
But yeah, if the above links aren't good enough (these were just the first relevant results I saw with a quick search), you can search through the recommended products and I'm sure you'll see some more results appear after _CLICKING_ through some that are closer to your preference!
